#ifndef DIO_H
#define DIO_H

/*==================================================================================================
*                                        INCLUDE FILES
==================================================================================================*/
#include "../../Common/Include/Std_Types.h"
#include "../../Config/Dio_Cfg.h" /* For DIO_DEV_ERROR_DETECT, DIO_VERSION_INFO_API etc. */

/*==================================================================================================
*                                           CONSTANTS
==================================================================================================*/

/* AUTOSAR Module and Vendor IDs */
#define DIO_MODULE_ID                     120U
#define DIO_VENDOR_ID                     0U /* Example Vendor ID, replace with actual */

/* AUTOSAR Instance ID */
#define DIO_INSTANCE_ID                   0U

/* Development Error Codes (if DIO_DEV_ERROR_DETECT is STD_ON) */
#if (DIO_DEV_ERROR_DETECT == STD_ON)
    #define DIO_E_PARAM_INVALID_CHANNEL_ID    0x0AU  /* Invalid channel requested */
    #define DIO_E_PARAM_INVALID_PORT_ID       0x14U  /* Invalid port requested */
    #define DIO_E_PARAM_INVALID_GROUP_ID      0x1FU  /* Invalid channel group requested */
    #define DIO_E_PARAM_POINTER               0x20U  /* API service called with a NULL pointer */
    #define DIO_E_UNINIT                      0xF0U  /* API service used without module initialization */
#endif /* (DIO_DEV_ERROR_DETECT == STD_ON) */

/* API Service IDs (for error reporting, mainly for Det_ReportError) */
#define DIO_READCHANNEL_ID                0x01U
#define DIO_WRITECHANNEL_ID               0x02U
#define DIO_READPORT_ID                   0x03U
#define DIO_WRITEPORT_ID                  0x04U
#define DIO_READCHANNELGROUP_ID           0x05U
#define DIO_WRITECHANNELGROUP_ID          0x06U
#define DIO_GETVERSIONINFO_ID             0x12U
#define DIO_FLIPCHANNEL_ID                0x11U
#define DIO_MASKEDWRITEPORT_ID            0x13U
#define DIO_INIT_ID                       0x10U


/* Physical States */
#ifndef STD_LOW
    #define STD_LOW     0x00U
#endif
#ifndef STD_HIGH
    #define STD_HIGH    0x01U
#endif

/*==================================================================================================
*                                      DEFINES AND MACROS
==================================================================================================*/

/*==================================================================================================
*                                             TYPES
==================================================================================================*/

/* Numeric ID of a DIO channel */
typedef uint8 Dio_ChannelType;

/* Numeric ID of a DIO port */
typedef uint8 Dio_PortType;

/* Type for the possible levels that a DIO channel can have (STD_LOW or STD_HIGH) */
typedef uint8 Dio_LevelType;

/* Type for the value of a DIO port (pins 0-15 for STM32F3) */
typedef uint16 Dio_PortLevelType;

/* Type for defining a channel group, which consists of several adjoining channels within a port */
typedef struct
{
    Dio_PortType      port;   /* The port on which the group is defined */
    uint8             offset; /* The offset of the channel group within the port */
    Dio_PortLevelType mask;   /* The mask defining the channels that belong to the group */
} Dio_ChannelGroupType;

/*
 * @brief Configuration structure for the DIO module.
 * @details This structure is used to pass configuration data to the DIO module.
 *          For post-build configurations, an instance of this type (defined in Dio_PBcfg.h)
 *          is passed to the Dio_Init function.
 * @note Actual configuration data (like channel mappings) will be in Dio_PBcfg.c/.h
 */
typedef struct
{
    /*
     * This structure can be empty if all configuration is done via Dio_Cfg.h (pre-compile)
     * or if Dio_Init receives a pointer to a more detailed post-build configuration structure
     * (e.g., generated by a configuration tool and residing in Dio_PBcfg.c).
     * For this structure, it's often a collection of pointers to actual configuration sets.
     */
    uint8 dummy; /* Placeholder to ensure the struct is not empty, actual content depends on config variant. */
                 /* For PB, this might point to an array of port configurations or channel configurations. */
} Dio_ConfigType;


/*==================================================================================================
*                                  FUNCTION PROTOTYPES
==================================================================================================*/

/* Function to initialize the Dio module */
extern FUNC(void, DIO_CODE) Dio_Init(P2CONST(Dio_ConfigType, AUTOMATIC, DIO_APPL_CONST) ConfigPtr);

/* Function to read the level of a single DIO channel */
extern FUNC(Dio_LevelType, DIO_CODE) Dio_ReadChannel(Dio_ChannelType ChannelId);

/* Function to write the level of a single DIO channel */
extern FUNC(void, DIO_CODE) Dio_WriteChannel(Dio_ChannelType ChannelId, Dio_LevelType Level);

/* Function to read the levels of all channels of a port */
extern FUNC(Dio_PortLevelType, DIO_CODE) Dio_ReadPort(Dio_PortType PortId);

/* Function to write the levels of all channels of a port */
extern FUNC(void, DIO_CODE) Dio_WritePort(Dio_PortType PortId, Dio_PortLevelType Level);

/* Function to read the levels of a group of channels */
extern FUNC(Dio_PortLevelType, DIO_CODE) Dio_ReadChannelGroup(P2CONST(Dio_ChannelGroupType, AUTOMATIC, DIO_APPL_CONST) ChannelGroupIdPtr);

/* Function to write new levels to a group of channels */
extern FUNC(void, DIO_CODE) Dio_WriteChannelGroup(P2CONST(Dio_ChannelGroupType, AUTOMATIC, DIO_APPL_CONST) ChannelGroupIdPtr, Dio_PortLevelType Level);

#if (DIO_VERSION_INFO_API == STD_ON)
/* Function to get the version information of the Dio module */
extern FUNC(void, DIO_CODE) Dio_GetVersionInfo(P2VAR(Std_VersionInfoType, AUTOMATIC, DIO_APPL_DATA) VersionInfo);
#endif

#if (DIO_FLIP_CHANNEL_API == STD_ON)
/* Function to flip the level of a single DIO channel */
extern FUNC(Dio_LevelType, DIO_CODE) Dio_FlipChannel(Dio_ChannelType ChannelId);
#endif

/* Function to write a masked value to a port (AUTOSAR 4.x extension) */
extern FUNC(void, DIO_CODE) Dio_MaskedWritePort(Dio_PortType PortId, Dio_PortLevelType Level, Dio_PortLevelType Mask);


/*==================================================================================================
*                                     EXTERNAL VARIABLES
==================================================================================================*/

/* Declare any global configuration pointer if needed, e.g. for post-build */
// extern P2CONST(Dio_ConfigType, DIO_VAR, DIO_APPL_CONST) Dio_GlobalConfigPtr;


#endif /* DIO_H */
